"""Setup focus areas mapped to implemented engine-guide capabilities and configuration groups.

These are presentation profiles, not switches that disable simulation dependencies.
"""

GOALS = [
    {"id": "operations", "title": "Operations day", "icon": "🚒",
     "description": "Break a main, dispatch crews and see how the town recovers.",
     "outcomes": "Restoration, network loading, pressure and reading rounds.",
     "capabilities": ["operations", "networks", "weather"],
     "environment": ["housing", "weather"], "town": ["electric", "water", "gas", "ami", "incidents", "operations"],
     "run": [], "map": True},
    {"id": "reading", "title": "Meter reading", "icon": "📡",
     "description": "Explore AMI, drive-by and manual reads, misses and access problems.",
     "outcomes": "Missed reads, estimates and consecutive no-access visits.",
     "capabilities": ["reading"], "environment": ["weather"], "town": ["ami"],
     "run": ["reading", "process"], "map": False},
    {"id": "vee", "title": "Validation & estimation (VEE)", "icon": "🔎",
     "description": "Inject unusual readings and test the rules and review team.",
     "outcomes": "Detection accuracy, estimates, exceptions and analyst backlog.",
     "capabilities": ["vee", "work"], "environment": [], "town": ["ami"],
     "run": ["reading", "anomalies", "vee", "process"], "map": False},
    {"id": "billing", "title": "Billing quality", "icon": "🧾",
     "description": "Test billing checks, tariffs, blocked bills and corrections.",
     "outcomes": "Billing errors, outsorts, rebills and cost to resolve.",
     "capabilities": ["billing", "work"], "environment": [], "town": ["customers_billing"],
     "run": ["billing", "process", "reading", "vee"], "map": False},
    {"id": "collections", "title": "Payments & collections", "icon": "💌",
     "description": "Follow invoices, late payments, arrangements and collections.",
     "outcomes": "Cash collected, overdue balances and collections workload.",
     "capabilities": ["collections"], "environment": [], "town": ["customers_billing"],
     "run": ["billing", "process"], "map": False},
    {"id": "fieldwork", "title": "Field work & maintenance", "icon": "🛠️",
     "description": "Plan crews, emergency response, meter work and maintenance.",
     "outcomes": "Work-order backlog, response times, overtime and maintenance compliance.",
     "capabilities": ["field", "fieldwork", "incidents"], "environment": ["weather"],
     "town": ["electric", "water", "gas", "ami", "incidents", "operations"],
     "run": ["field", "outages", "process"], "map": False},
    {"id": "contact", "title": "Contact centre", "icon": "☎️",
     "description": "See how bills, outages and service problems reach the phones.",
     "outcomes": "Waits, abandoned calls, repeat contacts and staffing pressure.",
     "capabilities": ["contact", "incidents"], "environment": ["weather"], "town": ["customers_billing", "incidents"],
     "run": ["contact", "outages", "billing"], "map": False},
    {"id": "everything", "title": "Test everything", "icon": "🌎",
     "description": "Explore the whole utility, with every setup setting available.",
     "outcomes": "All supported operations-day and utility-year views.",
     "capabilities": ["operations", "reading", "vee", "billing", "collections", "fieldwork", "contact"],
     "environment": ["*"], "town": ["*"], "run": ["*"], "map": True},
]
GOAL_IDS = {g["id"] for g in GOALS}
