export type ViewName='ne'|'nw'|'se'|'sw'|'top';
export type LayerName='water'|'gas'|'electric';
type Point=[number,number];
export type MapObject={id:string;name:string;kind:string;x:number;y:number;type:number;street:string;roadId:string|null;front?:Point;bearing?:number;solar?:boolean;ev?:boolean;technology?:string;placement?:string;footprint?:Point[];facing?:number;displayWidth?:number;lotPolygon?:Point[];entrance?:Point;driveway?:Point[];roadArc?:number;connections?:Record<LayerName,{id:string;premiseId:string;roadId:string;points:Point[]}>};
export type Road={id:string;osmId:number;name:string;roadClass:string;width:number;points:Point[]};
export type TownData={name:string;width:number;height:number;roads:Road[];buildings:MapObject[];equipment:MapObject[];overheadSpans?:{id:string;from:string;to:string}[];layout?:{spacingScale:number;homeIsoWidth:number;homeRoofWidth:number};trees:{x:number;y:number;size:number}[];land?:{kind:string;name:string;points:Point[]}[];footprints?:{points:Point[];name:string}[];source:{note:string;url:string;retrievedAt:string;mappedHomes?:number;infillHomes?:number}};
type Sprite={canvas:HTMLCanvasElement;width:number;height:number};
type Hit={object:MapObject;x:number;y:number;w:number;h:number};
const COLORS={electric:'#d98c38',water:'#559dc2',gas:'#d7b24e'};
const DARK={electric:'#825329',water:'#315f76',gas:'#877036'};
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
// House art has a consistent world size; address spacing only sizes the lawn.
const HOME_WIDTH={top:8,iso:11};
const EQUIPMENT_WIDTH={pole:{top:2.4,iso:6},pad:{top:2.2,iso:2.8},hydrant:{top:.7,iso:.8}};
const MAX_ZOOM=180;
// Actual camera positions for the four projection matrices, in east/south coordinates.
const CAMERA_BEARING={ne:3*Math.PI/4,nw:Math.PI/4,se:-3*Math.PI/4,sw:-Math.PI/4};
const ROOF_FRONT_BEARING=[90,90,90,90,90,90,135,90,135].map(v=>v*Math.PI/180);
export class TownEngine{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;data:TownData;
 options={view:'ne' as ViewName,underground:false,layers:{water:true,gas:true,electric:true},trees:true,labels:true};
 private onSelect:(o:MapObject|null)=>void;private onZoom:(v:number)=>void;private resize:ResizeObserver;private abort=new AbortController();private frame=0;private dead=false;
 private width=1000;private height=700;private dpr=1;private scale=1;private baseScale=1;private pan:Point=[0,0];private sprites:Record<string,Sprite[]>={};private hits:Hit[]=[];private selected:MapObject|null=null;private hovered:MapObject|null=null;private pointers=new Map<number,Point>();private dragStart:Point=[0,0];private moved=false;private pinchDistance=0;private loaded=false;
 constructor(canvas:HTMLCanvasElement,data:TownData,callbacks:{onSelect:(o:MapObject|null)=>void;onZoom:(n:number)=>void}){
  this.canvas=canvas;this.ctx=canvas.getContext('2d')!;this.data=data;this.onSelect=callbacks.onSelect;this.onZoom=callbacks.onZoom;
  this.resize=new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;this.dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*this.dpr);canvas.height=Math.round(r.height*this.dpr);this.fit()});this.resize.observe(canvas);
  const signal=this.abort.signal;
  canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();this.zoomBy(Math.exp(-e.deltaY*.0015),[e.clientX-r.left,e.clientY-r.top])},{passive:false,signal});
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,[e.clientX,e.clientY]);this.dragStart=[e.clientX,e.clientY];this.moved=false;canvas.style.cursor='grabbing';if(this.pointers.size===2)this.pinchDistance=this.getPinch()},{signal});
  canvas.addEventListener('pointermove',e=>{const old=this.pointers.get(e.pointerId);if(old){this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===2){const dist=this.getPinch();if(this.pinchDistance)this.zoomBy(dist/this.pinchDistance);this.pinchDistance=dist;this.moved=true}else{if(Math.hypot(e.clientX-this.dragStart[0],e.clientY-this.dragStart[1])>4)this.moved=true;this.pan[0]+=e.clientX-old[0];this.pan[1]+=e.clientY-old[1];this.drawSoon()}}else{const r=canvas.getBoundingClientRect();const obj=this.pick(e.clientX-r.left,e.clientY-r.top);if(obj?.id!==this.hovered?.id){this.hovered=obj;canvas.style.cursor=obj?'pointer':'grab';this.drawSoon()}}},{signal});
  canvas.addEventListener('pointerup',e=>{this.pointers.delete(e.pointerId);if(!this.moved){const r=canvas.getBoundingClientRect();this.select(this.pick(e.clientX-r.left,e.clientY-r.top))}canvas.style.cursor='grab';this.pinchDistance=0},{signal});
  canvas.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.pinchDistance=0;this.moved=true},{signal});
  canvas.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const center=this.inverse(this.width/2,this.height/2);const nearest=[...this.data.buildings].sort((a,b)=>Math.hypot(a.x-center[0],a.y-center[1])-Math.hypot(b.x-center[0],b.y-center[1]))[0];this.select(nearest);return}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='+'||e.key==='=')this.zoomBy(1.25);else if(e.key==='-')this.zoomBy(.8);else{this.pan[0]+=(e.key==='ArrowLeft'?60:e.key==='ArrowRight'?-60:0);this.pan[1]+=(e.key==='ArrowUp'?60:e.key==='ArrowDown'?-60:0);this.drawSoon()}}},{signal});
 }
 async load(){const bounds=await fetch('/assets/bounds.json').then(r=>r.json()) as Record<string,number[][]>;const items=[['ne',3,2],['nw',3,2],['se',3,2],['sw',3,2],['top',3,2],['equipment',4,2],['equipment-top',4,2],['diagonal',3,3],['diagonal-sides',3,2]] as const;await Promise.all(items.map(async([name,cols,rows])=>{const image=new Image();image.src=`/assets/${name}.png`;await image.decode();if(this.dead)return;this.sprites[name]=this.slice(image,cols,rows,bounds[name])}));if(this.dead)return;this.loaded=true;this.fit();const homes=this.data.buildings.filter(b=>b.kind==='home');const x=homes.reduce((s,b)=>s+b.x,0)/homes.length,y=homes.reduce((s,b)=>s+b.y,0)/homes.length;this.scale=this.baseScale*8;this.pan=[0,0];const p=this.project(x,y);this.pan=[this.width*.59-p[0],this.height*.54-p[1]];this.onZoom(800);this.drawSoon()}
 private slice(image:HTMLImageElement,cols:number,rows:number,bounds?:number[][]){const list:Sprite[]=[];const cw=image.naturalWidth/cols,ch=image.naturalHeight/rows;for(let index=0;index<cols*rows;index++){const rect=bounds?.[index]??[(index%cols)*cw,Math.floor(index/cols)*ch,(index%cols+1)*cw,(Math.floor(index/cols)+1)*ch];const x=Math.max(0,rect[0]),y=Math.max(0,rect[1]),w=Math.min(image.naturalWidth-x,rect[2]-rect[0]+1),h=Math.min(image.naturalHeight-y,rect[3]-rect[1]+1);const out=document.createElement('canvas');out.width=w;out.height=h;out.getContext('2d')!.drawImage(image,x,y,w,h,0,0,w,h);list.push({canvas:out,width:w,height:h})}return list}
 private getPinch(){const p=[...this.pointers.values()];return p.length===2?Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]):0}
 private project(x:number,y:number,z=0):Point{const dx=x-this.data.width/2,dy=y-this.data.height/2;let sx:number,sy:number;if(this.options.view==='top'){sx=dx;sy=dy}else if(this.options.view==='ne'){sx=(dx+dy)*.866;sy=(-dx+dy)*.5}else if(this.options.view==='nw'){sx=(dx-dy)*.866;sy=(dx+dy)*.5}else if(this.options.view==='se'){sx=(-dx+dy)*.866;sy=(-dx-dy)*.5}else{sx=(-dx-dy)*.866;sy=(dx-dy)*.5}return [this.width/2+this.pan[0]+sx*this.scale,this.height/2+this.pan[1]+(sy-z)*this.scale]}
 private inverse(sx:number,sy:number):Point{const px=(sx-this.width/2-this.pan[0])/this.scale,py=(sy-this.height/2-this.pan[1])/this.scale;let x,y;if(this.options.view==='top'){x=px;y=py}else if(this.options.view==='ne'){x=px/(2*.866)-py;y=px/(2*.866)+py}else if(this.options.view==='nw'){x=px/(2*.866)+py;y=py-px/(2*.866)}else if(this.options.view==='se'){x=-px/(2*.866)-py;y=px/(2*.866)-py}else{x=-px/(2*.866)+py;y=-px/(2*.866)-py}return [x+this.data.width/2,y+this.data.height/2]}
 fit(){const iso=this.options.view!=='top';const w=iso?(this.data.width+this.data.height)*.866:this.data.width;const h=iso?(this.data.width+this.data.height)*.5+65:this.data.height+65;const margin=this.width>950?260:50;this.baseScale=Math.min((this.width-margin-70)/w,(this.height-135)/h);this.baseScale=Math.max(.05,this.baseScale);this.scale=this.baseScale;this.pan=[this.width>950?100:0,25];this.onZoom(100);this.drawSoon()}
 setView(view:ViewName){if(this.options.view===view)return;const center=this.inverse(this.width/2,this.height/2);const ratio=this.scale/this.baseScale;this.options.view=view;this.fit();if(ratio>1.2){this.scale=this.baseScale*ratio;const p=this.project(...center);this.pan[0]+=this.width/2-p[0];this.pan[1]+=this.height/2-p[1];this.onZoom(Math.round(ratio*100))}this.drawSoon()}
 setUnderground(v:boolean){this.options.underground=v;this.drawSoon()}
 setLayer(k:LayerName,v:boolean){this.options.layers[k]=v;this.drawSoon()}
 setTrees(v:boolean){this.options.trees=v;this.drawSoon()}
 setLabels(v:boolean){this.options.labels=v;this.drawSoon()}
 zoomBy(factor:number,anchor?:Point){const a=anchor??[this.width/2,this.height/2];const w=this.inverse(...a);this.scale=clamp(this.scale*factor,this.baseScale*.65,this.baseScale*MAX_ZOOM);const after=this.project(...w);this.pan[0]+=a[0]-after[0];this.pan[1]+=a[1]-after[1];this.onZoom(Math.round(this.scale/this.baseScale*100));this.drawSoon()}
 focus(obj:MapObject){this.scale=obj.kind==='school'?3:Math.min(22,Math.max(12,this.width/65));const ratio=this.scale/this.baseScale;this.pan=[0,0];const p=this.project(obj.x,obj.y);const desiredX=this.width>750?this.width*.45:this.width*.42;this.pan=[desiredX-p[0],this.height*.62-p[1]];this.onZoom(Math.round(ratio*100));this.drawSoon()}
 select(obj:MapObject|null){this.selected=obj;this.onSelect(obj);this.drawSoon()}
 private pick(x:number,y:number){for(let i=this.hits.length-1;i>=0;i--){const h=this.hits[i];if(x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h)return h.object}return null}
 private drawSoon(){if(this.frame||this.dead)return;this.frame=requestAnimationFrame(()=>{this.frame=0;this.render()})}
 private line(points:Point[],color:string,width:number,z=0,dash:number[]=[]){
  const c=this.ctx,o=this.project(0,0,z),x=this.project(1,0,z),y=this.project(0,1,z);
  // Stroke in world space so road widths and equipment clearance use the same geometry.
  c.save();c.transform(x[0]-o[0],x[1]-o[1],y[0]-o[0],y[1]-o[1],o[0],o[1]);c.beginPath();
  points.forEach((p,i)=>{if(!i)c.moveTo(...p);else c.lineTo(...p)});c.strokeStyle=color;c.lineWidth=width;c.lineJoin='round';c.lineCap='round';c.setLineDash(dash);c.stroke();c.restore();
 }
 private polygon(points:Point[],fill:string,stroke?:string,z=0){const c=this.ctx;c.beginPath();points.forEach((p,i)=>{const a=this.project(p[0],p[1],z);i?c.lineTo(...a):c.moveTo(...a)});c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=.14*this.scale;c.stroke()}}
 private quad(x:number,y:number,w:number,h:number,b=0){const co=Math.cos(b),si=Math.sin(b);return [[-w/2,-h/2],[w/2,-h/2],[w/2,h/2],[-w/2,h/2]].map(([dx,dy])=>[x+dx*co-dy*si,y+dx*si+dy*co] as Point)}
 private offset(points:Point[],n:number){return points.map((p,i)=>{const a=points[Math.max(i-1,0)],b=points[Math.min(i+1,points.length-1)];const d=Math.hypot(b[0]-a[0],b[1]-a[1])||1;return [p[0]-(b[1]-a[1])/d*n,p[1]+(b[0]-a[0])/d*n] as Point})}
 private ground(){const {width:w,height:h}=this.data;this.polygon([[-22,-22],[w+22,-22],[w+22,h+22],[-22,h+22]],'#81946b','#70845c',-3);this.polygon([[-22,-22],[w+22,-22],[w+22,h+22],[-22,h+22]],'#b6c794');const c=this.ctx; // Seeded small ground marks are map surface texture, not building artwork.
  for(let i=0;i<1500;i++){const x=((i*197+47)%1045)/1045*w,y=((i*113+29)%415)/415*h;const p=this.project(x,y);c.fillStyle=i%3===0?'#a3b78055':'#d7dfb640';c.fillRect(p[0],p[1],Math.max(1,2*this.scale),Math.max(1,this.scale))}
  for(const land of this.data.land??[]){const colors:Record<string,string>={wetland:'#94b7a2',water:'#8fb9bd',wood:'#98af79',forest:'#98af79',park:'#a5c681',pitch:'#aec984',playground:'#dccda8',school:'#b5c698',grass:'#b3c594'};if(land.kind==='stream')this.line(land.points,'#8eb5ba',5);else this.polygon(land.points,colors[land.kind]??'#b5c793','#8da47d')}for(const fp of this.data.footprints??[])this.polygon(fp.points,'#adb6a0','#8f9e86');
  this.data.buildings.forEach((b,i)=>{const school=b.kind==='school';this.polygon(b.lotPolygon??this.quad(b.x,b.y,school?88:25,school?66:25,b.bearing??0),school?'#b3c08f':['#b3c38f','#bacb99','#afc18a'][i%3],'#97ad7c');if(b.front)this.line(b.driveway??[[b.x,b.y],b.front],'#dbd7c4',school?5:1.8)});
 }
 private roads(){for(const r of this.data.roads)this.line(r.points,'#92a279',r.width+7);for(const r of this.data.roads)this.line(r.points,'#e2ddca',r.width+4.6);for(const r of this.data.roads)this.line(r.points,'#b7b7a5',r.width+1.8);for(const r of this.data.roads)this.line(r.points,'#777f7d',r.width);for(const r of this.data.roads){this.line(r.points,'#89908b',r.width-.8);if(r.roadClass==='secondary')this.line(r.points,'#d3c18a',.35,0,[3.6,5.5])}
  if(this.options.underground){for(const r of this.data.roads){this.line(r.points,'#88735b',r.width+1);this.line(r.points,'#665948',r.width-1,-7);this.line(this.offset(r.points,-r.width/2),'#bb9b78',1.8);this.line(this.offset(r.points,r.width/2),'#584c3e',1,-5)}this.networks()}
 }
 private networks(){const keys:LayerName[]=['water','gas','electric'];for(const [i,key]of keys.entries()){if(!this.options.layers[key])continue;const z=this.options.view==='top'?0:-6-i*1.7;for(const r of this.data.roads){const p=this.offset(r.points,(i-1)*3.1);this.line(p,DARK[key],2.1,z);this.line(p,COLORS[key],1.35,z);this.line(this.offset(p,.13),'#ffffff66',.35,z+.08)}for(const b of this.data.buildings){if(!b.front)continue;const active=this.selected?.id===b.id;const p:Point[]=b.connections?.[key]?.points??[[b.x+(i-1)*2.2,b.y],b.front];this.ctx.globalAlpha=this.selected&&!active?0.26:.85;this.line(p,DARK[key],active?1.6:.9,z);this.line(p,COLORS[key],active?1:.6,z);this.ctx.globalAlpha=1;const end=this.project(...p[p.length-1],z);this.ctx.beginPath();this.ctx.arc(end[0],end[1],Math.max(1.5,this.scale*.4),0,Math.PI*2);this.ctx.fillStyle=COLORS[key];this.ctx.fill();this.ctx.strokeStyle=DARK[key];this.ctx.lineWidth=1;this.ctx.stroke()}}}
 private spriteFor(obj:MapObject){if(obj.kind==='home'||obj.kind==='school'){const top=this.options.view==='top';const angle=this.options.view==='top'?0:CAMERA_BEARING[this.options.view];const facing=obj.facing??-Math.PI/2;let relative=angle-facing;relative=Math.atan2(Math.sin(relative),Math.cos(relative));if(obj.type>=6){if(top)return this.sprites.diagonal?.[6+obj.type-6];const index=(Math.round(relative/(Math.PI/2))+4)%4;if(index===0)return this.sprites.diagonal?.[obj.type-6];if(index===2)return this.sprites.diagonal?.[3+obj.type-6];return this.sprites['diagonal-sides']?.[(index===1?3:0)+obj.type-6]}const bank=top?'top':relative>=0?(relative<Math.PI/2?'nw':'sw'):(relative>-Math.PI/2?'ne':'se');return this.sprites[bank]?.[obj.type]}return this.sprites[this.options.view==='top'?'equipment-top':'equipment']?.[obj.type]}
 private drawSprite(sprite:Sprite,x:number,y:number,width:number,top=false,alpha=1,rotation=0,anchor?:Point){const c=this.ctx,p=this.project(x,y);const dw=width*this.scale,dh=dw*sprite.height/sprite.width;const dx=p[0]-dw*(top?.5:anchor?.[0]??.5),dy=top?p[1]-dh/2:anchor?p[1]-dh*anchor[1]:p[1]-dh+width*this.scale*.18;c.globalAlpha=alpha;c.imageSmoothingEnabled=false;if(top&&rotation){c.save();c.translate(p[0],p[1]);c.rotate(rotation);c.drawImage(sprite.canvas,-dw/2,-dh/2,dw,dh);c.restore()}else c.drawImage(sprite.canvas,dx,dy,dw,dh);c.globalAlpha=1;return {x:dx,y:dy,w:dw,h:dh}}
 private objects(){this.hits=[];if(!this.loaded)return;const top=this.options.view==='top';const list:({y:number;draw:()=>void})[]=[];
  if(this.options.trees){for(const t of this.data.trees){const sp=this.sprites[top?'equipment-top':'equipment']?.[0];if(sp)list.push({y:this.project(t.x,t.y)[1],draw:()=>this.drawSprite(sp,t.x,t.y,t.size*(top?1:1.4),top,this.options.underground?.35:1)})}}
  for(const obj of [...this.data.buildings,...this.data.equipment])list.push({y:this.project(obj.x,obj.y)[1],draw:()=>{const sp=this.spriteFor(obj);if(!sp)return;const active=obj.id===this.selected?.id,hover=obj.id===this.hovered?.id;const width=obj.kind==='school'?(top?70:87):obj.kind==='home'?(top?this.data.layout?.homeRoofWidth??HOME_WIDTH.top:this.data.layout?.homeIsoWidth??HOME_WIDTH.iso):EQUIPMENT_WIDTH[obj.kind as keyof typeof EQUIPMENT_WIDTH]?.[top?'top':'iso']??1;
   if(active||hover){const p=this.project(obj.x,obj.y);this.ctx.beginPath();this.ctx.ellipse(p[0],p[1],(obj.kind==='school'?49:obj.kind==='home'?9:3)*this.scale,(top?8:4.5)*this.scale,0,0,Math.PI*2);this.ctx.fillStyle=active?'#f8da7277':'#fff6c350';this.ctx.fill();this.ctx.strokeStyle=active?'#ad7930':'#fef3c8';this.ctx.lineWidth=2;this.ctx.stroke()}
   const bounds=this.drawSprite(sp,obj.x,obj.y,width,top,this.options.underground&&!active?(obj.kind==='home'||obj.kind==='school'?.43:.75):1,top&&obj.front?(obj.facing??Math.PI/2)-(ROOF_FRONT_BEARING[obj.type]??Math.PI/2):0,obj.kind==='pole'?[.4,.99]:obj.kind==='pad'?[.5,.9]:obj.kind==='hydrant'?[.55,.95]:undefined);this.hits.push({object:obj,...bounds});
  }});list.sort((a,b)=>a.y-b.y).forEach(o=>o.draw());
  if(!top&&!this.options.underground&&this.options.layers.electric){
   const poles=new Map(this.data.equipment.filter(o=>o.kind==='pole').map(p=>[p.id,p]));
   const sprite=this.sprites.equipment?.[1];
   if(sprite)for(const span of this.data.overheadSpans??[]){
    const a=poles.get(span.from),b=poles.get(span.to);if(!a||!b)continue;
    // The center insulator in the sprite crop is the common endpoint for both spans.
    const attachment=(pole:MapObject):Point=>{const p=this.project(pole.x,pole.y);const w=EQUIPMENT_WIDTH.pole.iso*this.scale,h=w*sprite.height/sprite.width;return[p[0]+w*(.31-.4),p[1]-h*(.99-.125)]};
    const ap=attachment(a),bp=attachment(b);const sag=Math.min(2,Math.max(.6,Math.hypot(a.x-b.x,a.y-b.y)*.008))*this.scale;
    this.ctx.beginPath();this.ctx.moveTo(...ap);this.ctx.quadraticCurveTo((ap[0]+bp[0])/2,(ap[1]+bp[1])/2+sag,...bp);this.ctx.lineWidth=Math.max(.65,.05*this.scale);this.ctx.strokeStyle='#454c42';this.ctx.stroke();
   }
  }
 }
 private streetLabels(){if(!this.options.labels)return;const seen=new Set<string>();for(const r of this.data.roads){if(seen.has(r.name)||r.name==='Lane')continue;const L=r.points.slice(1).reduce((s,p,i)=>s+Math.hypot(p[0]-r.points[i][0],p[1]-r.points[i][1]),0);if(L<65)continue;seen.add(r.name);const mid=Math.floor((r.points.length-1)/2),a=this.project(...r.points[mid]),b=this.project(...r.points[mid+1]);const x=(a[0]+b[0])/2,y=(a[1]+b[1])/2;let angle=Math.atan2(b[1]-a[1],b[0]-a[0]);if(angle>Math.PI/2)angle-=Math.PI;if(angle<-Math.PI/2)angle+=Math.PI;this.ctx.save();this.ctx.translate(x,y);this.ctx.rotate(angle);this.ctx.font=`500 ${Math.max(10,Math.min(14,10*this.scale/this.baseScale))}px Arial`;this.ctx.textAlign='center';this.ctx.lineWidth=3;this.ctx.strokeStyle=this.options.underground?'#f8f4dfc9':'#fff9e7bd';this.ctx.strokeText(r.name,0,3);this.ctx.fillStyle='#44534a';this.ctx.fillText(r.name,0,3);this.ctx.restore()}}
 private tooltip(){const b=this.hovered;if(!b||this.pointers.size)return;const p=this.project(b.x,b.y,b.kind==='school'?60:40);const text=b.kind==='home'?`${b.name} · ${b.street}`:b.name;this.ctx.font='500 12px Arial';const w=this.ctx.measureText(text).width+22,x=clamp(p[0]-w/2,10,this.width-w-10),y=Math.max(65,p[1]-23);this.ctx.fillStyle='#253e32';this.ctx.beginPath();this.ctx.roundRect(x,y,w,28,6);this.ctx.fill();this.ctx.fillStyle='#fffdf4';this.ctx.textAlign='left';this.ctx.fillText(text,x+11,y+18)}
 private render(){const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.width,this.height);c.fillStyle='#e7e9d9';c.fillRect(0,0,this.width,this.height);c.save();c.beginPath();[[-22,-22],[this.data.width+22,-22],[this.data.width+22,this.data.height+22],[-22,this.data.height+22]].forEach((p,i)=>{const q=this.project(p[0],p[1]);i?c.lineTo(...q):c.moveTo(...q)});c.closePath();c.clip();this.ground();this.roads();c.restore();this.objects();this.streetLabels();this.tooltip()}
 drawPortrait(canvas:HTMLCanvasElement,obj:MapObject){const c=canvas.getContext('2d')!;c.clearRect(0,0,canvas.width,canvas.height);const sp=this.spriteFor(obj);if(!sp)return;const s=Math.min((canvas.width-50)/sp.width,(canvas.height-18)/sp.height);c.imageSmoothingEnabled=false;c.drawImage(sp.canvas,(canvas.width-sp.width*s)/2,(canvas.height-sp.height*s)/2,sp.width*s,sp.height*s)}
 destroy(){this.dead=true;cancelAnimationFrame(this.frame);this.abort.abort();this.resize.disconnect()}
}
