import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const modulePath = process.env.PLAYWRIGHT_MODULE || new URL('../../out/civic-atlas/browser/node_modules/playwright-core/index.mjs', import.meta.url).href;
const { chromium } = await import(modulePath);
const output = process.env.ATLAS_WELCOME_OUTPUT || fileURLToPath(new URL('../../out/civic-atlas/welcome-review/', import.meta.url));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader','--no-proxy-server'] });
const errors=[];
try {
 const page=await browser.newPage({viewport:{width:1600,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.ATLAS_URL || 'http://127.0.0.1:8040') + '/#welcome');
 await page.waitForFunction(()=>document.body.dataset.ready==='true'||document.querySelector('#retry')?.hidden===false,null,{timeout:120000});
 assert.equal(await page.evaluate(()=>document.body.dataset.ready),'true',await page.locator('#boot-message').textContent());
 await page.locator('#welcome-page img').evaluateAll(async images=>{images.forEach(img=>img.loading='eager');await Promise.all(images.map(img=>img.decode()));});
 const account=page.locator('#welcome-account-button');
 await account.click();
 assert.equal(await account.getAttribute('aria-expanded'),'true');
 await page.screenshot({animations:'disabled',path:`${output}/account-menu.png`});
 await page.keyboard.press('Escape');
 assert.equal(await account.getAttribute('aria-expanded'),'false');
 assert.equal(await account.evaluate(e=>e===document.activeElement),true);
 await account.press('ArrowDown');
 assert.equal(await page.locator('#welcome-account-panel button').first().evaluate(e=>e===document.activeElement),true);
 await page.keyboard.press('Tab');
 await page.keyboard.press('Enter');
 assert.equal(await page.locator('#welcome-sign-in-dialog').evaluate(d=>d.open),true);
 assert.match(await page.locator('#welcome-sign-in-dialog').innerText(),/has not been configured/);
 assert.equal(await page.locator('#welcome-sign-in-dialog input').count(),0);
 await page.screenshot({animations:'disabled',path:`${output}/sign-in-dialog.png`});
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>document.activeElement===document.querySelector('#welcome-account-button'));
 assert.equal(await account.evaluate(e=>e===document.activeElement),true);
 await account.click();
 await page.locator('.welcome-copy h1').click();
 assert.equal(await account.getAttribute('aria-expanded'),'false');
 for(const width of [1600,1024,390]) {
   await page.setViewportSize({width,height:width===1600?1000:850});
   await page.evaluate(()=>scrollTo(0,0));
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`no overflow at ${width}`);
   await page.screenshot({animations:'disabled',path:`${output}/welcome-${width}.png`,fullPage:true});
 }
 await page.setViewportSize({width:1600,height:1000});
 await page.locator('#welcome-chapter-1').scrollIntoViewIfNeeded();
 await page.waitForFunction(()=>document.querySelector('[data-story-jump="1"]').getAttribute('aria-current')==='step');
 await page.screenshot({animations:'disabled',path:`${output}/story-setup.png`});
 await page.locator('[data-story-jump="3"]').click();
 await page.waitForFunction(()=>document.querySelector('[data-story-jump="3"]').getAttribute('aria-current')==='step');
 await page.waitForFunction(()=>Math.abs(document.querySelector('#welcome-chapter-3').getBoundingClientRect().top)<innerHeight);
 await page.screenshot({animations:'disabled',path:`${output}/story-connections.png`});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.locator('[data-story-jump="0"]').click();
 await page.waitForFunction(()=>document.querySelector('[data-story-jump="0"]').getAttribute('aria-current')==='step');
 assert.equal(await page.locator('.welcome-story-scene.is-current>img').evaluate(e=>getComputedStyle(e).transform),'none');
 assert.equal(await page.locator('.welcome-story-scene.is-current').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');
 await page.evaluate(()=>scrollTo(0,0));
 await account.click();
 await page.locator('#welcome-sign-in').click();
 await page.locator('#welcome-sign-in-continue').click();
 await page.waitForFunction(()=>document.body.dataset.view==='overview');
 assert.equal(await page.locator('#welcome-sign-in-dialog').evaluate(d=>d.open),false);
 assert.equal(await page.locator('.sidebar').isVisible(),true);
 assert.deepEqual(errors,[]);
 console.log('PASS: account keyboard/Escape/outside, honest sign-in dialog and workspace route; illustrated scroll chapters; reduced-motion; 1600/1024/390 no overflow; no page errors.');
} finally { await browser.close(); }
