import test from 'node:test';
import assert from 'node:assert/strict';
import {customerIndex,customerProfile,demoCustomers} from '../dist/customer.js';
import {customerMarkup,billingMarkup} from '../dist/customer-view.js';
const at='2026-07-15T12:00:00Z';
function fixture(){return {seed:'42',premises:[{id:'P1',accountId:'CA-new',address:'1 Main St',occupied:true,services:{electric:'SP1'}}],businessPartners:[{id:'BP-new',name:'Alex <script>alert(1)</script>'},{id:'BP-old',name:'Former tenant'}],accounts:[{id:'CA-new',businessPartnerId:'BP-new',currency:'CAD',validFrom:'2026-06-01',validTo:null},{id:'CA-old',businessPartnerId:'BP-old',validTo:'2026-06-01'}],servicePoints:[{id:'SP1',installationId:'IN1'}],installations:[{id:'IN1'}],meters:[{id:'M1',servicePointId:'SP1',technology:'AMI',installedAt:'2020-01-01',removedAt:null}],registers:[{id:'R1',meterId:'M1',direction:'import',unit:'kWh'},{id:'R2',meterId:'M1',direction:'export',unit:'kWh'}],contracts:[{id:'C-new',accountId:'CA-new',installationId:'IN1',validFrom:'2026-06-01',validTo:null},{id:'C-old',accountId:'CA-old',installationId:'IN1',validFrom:'2020-01-01',validTo:'2026-06-01'}],sampleReads:[{id:'READ',premiseId:'P1',registerId:'R1',commodity:'electric',unit:'kWh',consumption:null,readStatus:'missing',veeStatus:'not_processed'}],billingDocuments:[{id:'BILL1',accountId:'CA-new',totalAmount:25,billStatus:'released'},{id:'BILL-old',accountId:'CA-old',totalAmount:1000}],invoices:[{id:'INV1',billingDocumentIds:['BILL1'],total:25,status:'issued'},{id:'INV-old',accountId:'CA-old',total:1000}]};}
test('customer joins preserve premise identity, account validity, separate registers and account-scoped documents',()=>{const t=fixture(),i=customerIndex(t),h=t.premises[0],p=customerProfile(t,i,h,at);assert.equal(p.partner.id,'BP-new');assert.equal(p.contracts.length,2);assert.equal(p.services[0].meters[0].registers.length,2);assert.deepEqual(p.bills.map(b=>b.id),['BILL1']);assert.deepEqual(p.invoices.map(b=>b.id),['INV1']);const previous=customerProfile(t,i,h,'2026-05-01');assert.equal(previous.account.id,'CA-old');assert.equal(previous.home.id,p.home.id);});
test('profile preserves missing reads and balances, escapes text and never calculates charges',()=>{const t=fixture(),p=customerProfile(t,customerIndex(t),t.premises[0],at);const customer=customerMarkup(p,p.reads),billing=billingMarkup(p,p.reads);assert.match(customer,/Not received/);assert.match(billing,/Not supplied/);assert.match(billing,/not processed/);assert.doesNotMatch(billing,/1,000/);const empty={...p,bills:[],invoices:[],account:{}};const html=billingMarkup(empty,p.reads);assert.match(html,/No billing documents supplied/);assert.doesNotMatch(html,/\$0/);});
test('fictional demo names are reproducible, exported and do not mutate imported snapshots',()=>{const t=fixture(),before=JSON.stringify(t),a=demoCustomers(t),b=demoCustomers(t);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(JSON.stringify(t),before);assert.equal(a.accounts[0].premiseId,'P1');assert.equal(a.businessPartners[0].synthetic,true);});
