import * as THREE from '/viewer/vendor/three.module.js';
import {AtlasMap} from './map.js';
import {createBlockPlate, BLOCK, SECOND_BLOCK} from './map-block-plate.js';
const $=id=>document.getElementById(id);
const data=await (await fetch('/atlas/api/bootstrap')).json(),town=data.snapshot;
const twoBlocks=new URLSearchParams(location.search).get('blocks')==='2';const activeIds=twoBlocks?[...BLOCK.ids,...SECOND_BLOCK.ids]:BLOCK.ids;let selected=null,plate=null,secondPlate=null;
const notify=text=>$('status').textContent=text;
const map=new AtlasMap($('map'),town,{onSelect:select,onSketch:()=>{},notify});
await map.visualReady;
function frame(){const s=map.scene;const center=twoBlocks?{x:125,z:-143}:BLOCK.center;s.controls.target.set(center.x,s.heightAt(center.x,center.z),center.z);s.camera.position.copy(s.controls.target).addScaledVector(map.direction,(twoBlocks?190:140)/.65);map.updateProjection();}
frame();
const debug=new THREE.Group();debug.visible=false;
for(const p of town.premises.filter(p=>activeIds.includes(p.id))){const b=town.buildings.find(b=>b.id===p.buildingId);const points=b.footprint.polygon.map(v=>new THREE.Vector3(v.x,map.scene.heightAt(v.x,v.z)+.4,v.z));points.push(points[0]);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#ff228c',depthTest:false,transparent:true,toneMapped:false}));line.renderOrder=20;debug.add(line);const anchor=new THREE.Mesh(new THREE.SphereGeometry(.7,8,6),new THREE.MeshBasicMaterial({color:'#ff228c',depthTest:false,transparent:true}));anchor.position.set(p.x,map.scene.heightAt(p.x,p.z)+.5,p.z);anchor.renderOrder=20;debug.add(anchor);}
map.scene.root.add(debug);
async function select(home){selected=home;map.select(home);plate?.liftOverlays();const detail=await(await fetch('/atlas/api/premises/'+encodeURIComponent(home.id))).json();$('property').replaceChildren();const title=document.createElement('h2');title.textContent=home.address;$('property').append(title);for(const [label,value]of [['Saved property',home.id],['Residents',home.occupants],['Storeys',home.stories],['Block artwork',activeIds.includes(home.id)?'Inside study':'Outside study']]){const row=document.createElement('div');row.className='data';const span=document.createElement('span');span.textContent=label;const strong=document.createElement('strong');strong.textContent=String(value);row.append(span,strong);$('property').append(row);}window.blockDetail=detail;notify(home.address+' · original saved property selected');}
function enable(value){const enabled=plate?.setEnabled(value)||false;secondPlate?.setEnabled(enabled);$('individual').setAttribute('aria-pressed',String(!enabled));$('baked').setAttribute('aria-pressed',String(enabled));notify(enabled?'Generated block · original property picking and utility topology':'Individual assets · the same saved block');}
$('individual').onclick=()=>enable(false);$('baked').onclick=()=>enable(true);$('frame').onclick=frame;$('debug').onchange=()=>{debug.visible=$('debug').checked;map.request();};$('layer').onchange=()=>{map.setLayer($('layer').value);plate?.liftOverlays();};$('invalidate').onclick=()=>{plate?.invalidate('Source geometry changed in this demonstration');secondPlate?.invalidate('Source geometry changed in this demonstration');enable(false);notify('Stale artwork disabled. Original assets and property selection remain available.');$('baked').disabled=true;};
plate=createBlockPlate(map,{metadataUrl:'./assets/civic-block-pine-willow.json',imageUrl:'./assets/civic-block-pine-willow.png'});
if(twoBlocks){secondPlate=createBlockPlate(map,{block:SECOND_BLOCK,manageOverlays:false,metadataUrl:'./assets/civic-block-oak-birch.json',imageUrl:'./assets/civic-block-oak-birch.png'});$('baked').textContent='Generated blocks';document.querySelector('header small').textContent='Fourteen saved homes · two adjacent street blocks';document.querySelector('aside h2').textContent='Two blocks. One town.';document.querySelector('aside > p').textContent='Two separately generated subdivisions share the same saved Oak Avenue. Compare their edges, planting and scale while the road and utility network remain authoritative.';}await Promise.all([plate.ready,secondPlate?.ready]);
const allReady=plate.stats.ready&&(!twoBlocks||secondPlate.stats.ready);$('baked').disabled=!allReady;
notify(allReady?'Compare individual assets with one generated subdivision.':'Individual assets ready · generated block artwork awaiting review.');
window.blockStudy={map,town,plate,secondPlate,twoBlocks,debug,frame,select,enable,selected:()=>selected,constants:BLOCK,activeIds};document.body.dataset.ready='true';
