const $=id=>document.getElementById(id);
const esc=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let record=null,pending=null,busy=false,storageOK=true;
const storageKey='world-customer-cashflow-pending';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value/100);
const dollars=value=>Math.floor(value/100)+'.'+String(value%100).padStart(2,'0');
function cents(value){const text=value.trim();if(!/^\d+(\.\d{1,2})?$/.test(text))throw Error('Enter a nonnegative USD amount with at most two decimal places.');const [whole,frac='']=text.split('.');const amount=BigInt(whole)*100n+BigInt(frac.padEnd(2,'0'));if(amount>1000000000000n)throw Error('Amount exceeds the supported cash limit.');return Number(amount);}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
function controls(){for(const el of document.querySelectorAll('input,select,button'))el.disabled=busy||!!pending;for(const el of document.querySelectorAll('#policy input,#policy select,#policy button'))el.disabled=busy||!!pending||!storageOK||!record?.financeConfigured||record?.cohortBlocked;$('retry').hidden=!pending;$('retry').disabled=busy||!storageOK;$('older').disabled=busy||!!pending||!record?.nextBefore;}
async function request(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const value=await response.json();if(!response.ok){const error=Error(value.error||'Request failed.');error.rejected=response.status>=400&&response.status<500;throw error;}return value;}
async function load(premise,before=null){
 const next=await request('/api/customer-cashflow?premise='+encodeURIComponent(premise)+(before?'&before='+encodeURIComponent(before):''));
 if(record&&record.worldFingerprint!==next.worldFingerprint)throw Error('World identity changed. Reload before editing.');record=next;
 $('premise').value=record.premiseId;$('identity').textContent=record.environmentId+' · '+record.premiseId+' · next physical day '+record.through+' · cashflow revision '+record.revision;
 $('overview').hidden=$('settings').hidden=$('historySection').hidden=false;
 $('state').textContent=record.cohortBlocked?'This cohort is vacant or has changed. New cashflow is blocked; existing reservations remain protected.':!record.financeConfigured?'Configure this premise in Customer cash and payments first.':!record.configured?'Recurring cashflow is not configured.':record.policy.active?'Recurring cashflow is active.':'Recurring cashflow is paused.';
 $('balances').innerHTML=record.financeConfigured?`<p>Cash<strong>${money(record.cashCents)}</strong></p><p>Reserved for payments<strong>${money(record.reservedCashCents)}</strong></p><p>Simulated recipient<strong>${esc(record.recipientRef)}</strong></p>`:'';
 const policy=record.policy;for(const [prefix,stream] of [['income',policy?.income],['expense',policy?.essentialExpense]]){if(stream){$(prefix+'Amount').value=dollars(stream.amountCents);$(prefix+'First').value=stream.firstDate;$(prefix+'Interval').value=stream.intervalDays;}else{$(prefix+'First').value=record.through;$(prefix+'Amount').value=prefix==='income'?'1000.00':'50.00';$(prefix+'Interval').value=prefix==='income'?'14':'1';}}
 $('active').checked=policy?.active??false;$('shortfall').value=policy?.insufficientCashPolicy??'available-cash';
 $('history').innerHTML=record.history.length?record.history.map(h=>`<tr><td>${esc(h.day)}<br>revision ${h.policyRevision}</td><td>${money(h.incomeDueCents)} / ${money(h.incomeCreditedCents)} / ${money(h.incomeSkippedCents)}</td><td>${money(h.expenseDueCents)} / ${money(h.expensePaidCents)} / ${money(h.expenseUnfundedCents)}</td><td>${money(h.openingCashCents)} / ${money(h.closingCashCents)}</td><td>${money(h.reservedCashCents)}</td><td>${esc(h.status)}<br>Income: ${esc(h.incomeStatus)}<br>Expense: ${esc(h.expenseStatus)}</td></tr>`).join(''):'<tr><td colspan="6">No occurrences recorded on this page.</td></tr>';controls();
}
async function send(){
 if(busy)return;
 if(!pending){try{pending={schemaVersion:'world-customer-cashflow/1',commandId:crypto.randomUUID(),environmentId:record.environmentId,runId:record.runId,worldFingerprint:record.worldFingerprint,actorId:'world-admin',expectedRevision:record.revision,effectiveDate:record.through,action:'configure',premiseId:record.premiseId,recipientRef:record.recipientRef,active:$('active').checked,income:{amountCents:cents($('incomeAmount').value),firstDate:$('incomeFirst').value,intervalDays:Number($('incomeInterval').value)},essentialExpense:{amountCents:cents($('expenseAmount').value),firstDate:$('expenseFirst').value,intervalDays:Number($('expenseInterval').value)},insufficientCashPolicy:$('shortfall').value,incomeOverflowPolicy:'skip-with-record',reason:$('reason').value.trim(),causalReference:'local-world-controls'};sessionStorage.setItem(storageKey,JSON.stringify(pending));}catch(e){pending=null;message(e.message||'Enable session storage before editing.',true);return;}}
 busy=true;controls();message('Recording recurring cashflow assumptions…');
 try{await request('/api/customer-cashflow',pending);const premise=pending.premiseId;pending=null;sessionStorage.removeItem(storageKey);await load(premise);message('Saved. The next due physical day applies income, then expenses, before utility-payment decisions.');}
 catch(e){if(e.rejected){pending=null;sessionStorage.removeItem(storageKey);}message(e.message+(pending?' Outcome uncertain. Retry the exact retained command.':' Load the premise again before editing.'),true);}
 finally{busy=false;controls();}
}
async function lookup(before=null){if(busy||pending)return;busy=true;controls();try{await load($('premise').value.trim(),before);message('Cashflow scenario loaded.');}catch(e){record=null;message(e.message,true);}finally{busy=false;controls();}}
$('lookup').onsubmit=e=>{e.preventDefault();lookup();};$('policy').onsubmit=e=>{e.preventDefault();send();};$('retry').onclick=send;$('latest').onclick=()=>lookup();$('older').onclick=()=>lookup(record.nextBefore);
try{pending=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(pending){$('premise').value=pending.premiseId;message('A retained command needs confirmation. Retry its exact original world, cohort and payload.');}else{const premise=new URLSearchParams(location.search).get('premise');if(premise){$('premise').value=premise;lookup();}}}catch{storageOK=false;message('Session storage could not be read. Enable it before changing cashflow.',true);}controls();
